### ISSUE TITLE
Write response letter for reviewers

### ISSUE THREAD

**Issue by graciellehigino** [graciellehigino/ms_range_interactions#72]
Address specific commentaries:
- [x] 1. Background in the intro #66 #70
- [x] 2. Too little citations #66 #70
- [x] 3. Too many citations (tables and figures in the discussion section) #65 
- [x] 4. Accuracy of range maps #66 #70 
- [ ] 5. GBIF data - cleaning and retrieving #67
- [ ] 5. Absence data from occurrence points (where does this comment come from, really?)
> **Warning**
> This is the most important commentary, which led to the decision of major review. It's worth reviewing the text to double-check we are not misleading the reader to understand we are creating absence data from GBIF rather than "erasing" the range where preys are not present.
- [x] 6. Lines 7-9: Please provide a short description for each example (taxonomic errors, geographic inaccuracy, or sampling biases). #65 
- [x] 7. Lines 9-11: Please cite studies that have done this before! If there are no previous studies, it is important to highlight the novelty of your study. #70 
- [x] 8. Lines 21-23: Are the cited literature examples of models that do not take ecological interactions into account? Use e.g. before. 
- [x] 9. Lines 68-70: This mismatch cannot just be a result of the overestimation of the predator’s range but it could be the result of misestimating both the predator's and prey's range. Please rephrase the sentence. #65

**Comment by graciellehigino** [comment]
@tpoisot Maybe could you help us with item 5? I have read the text too many times already and can't quite spot where we could have written something misleading. Apparently is something they would like to see addressed in the _Validation_ section.

**Comment by tpoisot** [comment]
Can you email me the reviews? There's little I can do without them

**Comment by graciellehigino** [comment]
Done! Details, files, line numbers and all included.

Thanks so much!
